[package]
name = "stats"
version = "0.1.3"
authors = ["OriginCode <self@origincode.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factorial = "0.2"
